src/Entity/Chofer.php
<?php

namespace App\Entity;

use Doctrine\DBAL\Types\StringType;
use Doctrine\ORM\Mapping as ORM;

/**
 * Chofer
 *
 * @ORM\Table(name="chofer")
 * @ORM\Entity(repositoryClass="App\Repository\ChoferRepository")
 */
class Chofer
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     */

    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255, nullable=true)
     */
    private $nombre;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="licencia_emision", type="date", nullable=true)
     */
    private $licencia_emision;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="licenciaVencimiento", type="date", nullable=true)
     */
    private $licencia_vencimiento;


    /**
     * @var string
     *
     * @ORM\Column(name="noLicenciaOperativa", type="string", length=255, nullable=true)
     */
    private $noLicenciaOperativa;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="recalificacionEmision", type="date", nullable=true)
     */
    private $recalificacion_emision;
    //    /**
    //     * @var int
    //     *
    //     * @ORM\Column(name="tiempo_servicio", type="integer", nullable=true)
    //     */
    //    private $tiempoServicio;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="recalificacionVencimiento", type="date", nullable=true)
     */
    private $recalificacionVencimiento;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="examenMedicoEmision", type="date", nullable=true)
     */
    private $examenMedicoEmision;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="examenMedicoVencimiento", type="date", nullable=true)
     */
    private $examenMedicoVencimiento;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="examenPsicofisiologicoEmision", type="date", nullable=true)
     */
    private $examenPsicofisiologicoEmision;
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="examenPsicofisiologicoVencimiento", type="date", nullable=true)
     */
    private $examenPsicofisiologicoVencimiento;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Omnibus", inversedBy="chofer")
     * @ORM\JoinColumn(name="omnibus_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $omnibus;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EscogidaTurno", mappedBy="chofer")
     */
    protected $escogida;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Trabajador", inversedBy="chofer")
     * @ORM\JoinColumn(name="trabajador_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $trabajador;


    public function __toString()
    {
        return $this->getNombre();
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->escogida = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add escogida
     *
     * @param \App\Entity\EscogidaTurno $escogida
     *
     * @return Chofer
     */
    public function addEscogida(\App\Entity\EscogidaTurno $escogida)
    {
        $this->escogida[] = $escogida;

        return $this;
    }

    /**
     * Remove escogida
     *
     * @param \App\Entity\EscogidaTurno $escogida
     */
    public function removeEscogida(\App\Entity\EscogidaTurno $escogida)
    {
        $this->escogida->removeElement($escogida);
    }

    /**
     * @param mixed $escogida
     */
    public function setEscogida($escogida)
    {
        $this->escogida = $escogida;
    }

    /**
     * @return mixed
     */
    public function getEscogida()
    {
        return $this->escogida;
    }

    /**
     * @param \DateTime $examenMedicoEmision
     */
    public function setExamenMedicoEmision($examenMedicoEmision)
    {
        $this->examenMedicoEmision = $examenMedicoEmision;
    }

    /**
     * @return \DateTime
     */
    public function getExamenMedicoEmision()
    {
        return $this->examenMedicoEmision;
    }

    /**
     * @param \DateTime $examenMedicoVencimiento
     */
    public function setExamenMedicoVencimiento($examenMedicoVencimiento)
    {
        $this->examenMedicoVencimiento = $examenMedicoVencimiento;
    }

    /**
     * @return \DateTime
     */
    public function getExamenMedicoVencimiento()
    {
        return $this->examenMedicoVencimiento;
    }

    /**
     * @param \DateTime $examenPsicofisiologicoEmision
     */
    public function setExamenPsicofisiologicoEmision($examenPsicofisiologicoEmision)
    {
        $this->examenPsicofisiologicoEmision = $examenPsicofisiologicoEmision;
    }

    /**
     * @return \DateTime
     */
    public function getExamenPsicofisiologicoEmision()
    {
        return $this->examenPsicofisiologicoEmision;
    }

    /**
     * @param \DateTime $examenPsicofisiologicoVencimiento
     */
    public function setExamenPsicofisiologicoVencimiento($examenPsicofisiologicoVencimiento)
    {
        $this->examenPsicofisiologicoVencimiento = $examenPsicofisiologicoVencimiento;
    }

    /**
     * @return \DateTime
     */
    public function getExamenPsicofisiologicoVencimiento()
    {
        return $this->examenPsicofisiologicoVencimiento;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @param \DateTime $licencia_emision
     */
    public function setLicenciaEmision($licencia_emision)
    {
        $this->licencia_emision = $licencia_emision;
    }

    /**
     * @return \DateTime
     */
    public function getLicenciaEmision()
    {
        return $this->licencia_emision;
    }

    /**
     * @param \DateTime $licencia_vencimiento
     */
    public function setLicenciaVencimiento($licencia_vencimiento)
    {
        $this->licencia_vencimiento = $licencia_vencimiento;
    }

    /**
     * @return \DateTime
     */
    public function getLicenciaVencimiento()
    {
        return $this->licencia_vencimiento;
    }

    /**
     * @param string $noLicenciaOperativa
     */
    public function setNoLicenciaOperativa($noLicenciaOperativa)
    {
        $this->noLicenciaOperativa = $noLicenciaOperativa;
    }

    /**
     * @return string
     */
    public function getNoLicenciaOperativa()
    {
        return $this->noLicenciaOperativa;
    }

    /**
     * @param mixed $omnibus
     */
    public function setOmnibus($omnibus)
    {
        $this->omnibus = $omnibus;
    }

    /**
     * @return mixed
     */
    public function getOmnibus()
    {
        return $this->omnibus;
    }

    /**
     * @param \DateTime $recalificacionVencimiento
     */
    public function setRecalificacionVencimiento($recalificacionVencimiento)
    {
        $this->recalificacionVencimiento = $recalificacionVencimiento;
    }

    /**
     * @return \DateTime
     */
    public function getRecalificacionVencimiento()
    {
        return $this->recalificacionVencimiento;
    }

    /**
     * @param \DateTime $recalificacion_emision
     */
    public function setRecalificacionEmision($recalificacion_emision)
    {
        $this->recalificacion_emision = $recalificacion_emision;
    }

    /**
     * @return \DateTime
     */
    public function getRecalificacionEmision()
    {
        return $this->recalificacion_emision;
    }

    /**
     * @param mixed $trabajador
     */
    public function setTrabajador($trabajador)
    {
        $this->trabajador = $trabajador;
    }

    /**
     * @return mixed
     */
    public function getTrabajador()
    {
        return $this->trabajador;
    }

    /**
     * @param string $nombre
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    }

    /**
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }
}

src/Form/ChoferType.php
<?php

namespace App\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChoferType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('omnibus', EntityType::class, array('class' => 'App\Entity\Omnibus', 'multiple' => false, 'expanded' => false))
            ->add('recalificacion_emision', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('recalificacionVencimiento', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('noLicenciaOperativa')
            ->add('examenMedicoEmision', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('examenMedicoVencimiento', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('examenPsicofisiologicoEmision',  DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('licencia_emision', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('licencia_vencimiento', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ])
            ->add('examenPsicofisiologicoVencimiento', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['data-language' => 'es', 'class' => 'datepicker-here', 'data-date-format' => 'yyyy-mm-dd'],
            ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Chofer'
        ));
    }
}

src/Controller/ChoferController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Chofer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Doctrine\DBAL\Driver\Connection;

// use this in case of security from controller @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_ESPECIALISTA_OPERACIONES')")

/**
 *
 * Función para llamar a la plantilla de administración
 *
 */
class ChoferController extends AbstractController
{

    /**
     * Lists all Chofer entities.
     *
     */
    public function indexAction(COnnection $connection)
    {
        $em = $connection;

        $query = 'SELECT
           chofer.nombre,
           trabajador.ci,
           trabajador.codigo,
           chofer.nolicenciaoperativa,
           chofer.trabajador_id,
           chofer.licenciavencimiento,
           chofer.examenmedicovencimiento,
           chofer.examenpsicofisiologicovencimiento
        FROM
           public.chofer,
           public.trabajador
        WHERE
           trabajador.id = chofer.trabajador_id';

        $stmt = $em->prepare($query);
        $params = array();
        $stmt->execute($params);
        $reportes = $stmt->fetchAll();
        return $this->render('chofer/index.html.twig', array(
            'reportes' => $reportes
        ));
    }

    /**
     * Creates a new Chofer entity.
     *
     */
    public function newAction(Request $request)
    {
        return null;
    }

    /**
     * Finds and displays a Chofer entity.
     *
     */
    public function showAction(Chofer $chofer)
    {
        return $this->render('chofer/show.html.twig', array(
            'chofer' => $chofer,
        ));
    }

    /**
     * Displays a form to edit an existing Chofer entity.
     *
     */
    public function editAction(Request $request, Chofer $chofer)
    {
        $editForm = $this->createForm('App\Form\ChoferType', $chofer);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($chofer);
            $em->flush();

            $this->addFlash('notice', 'Se ha editado correctamente!');

            return $this->redirectToRoute('chofer_index', array('id' => $chofer->getId()));
        }

        return $this->render('chofer/edit.html.twig', array(
            'chofer' => $chofer,
            'edit_form' => $editForm->createView(),
        ));
    }

    /**
     * Deletes a Chofer entity.
     *
     */
    public function deleteAction(Request $request, Chofer $chofer)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($chofer);
        $em->flush();

        return $this->redirectToRoute('chofer_index');
    }

    /**
     * Creates a form to delete a Chofer entity.
     *
     * @param Chofer $chofer The Chofer entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Chofer $chofer)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('chofer_delete', array('id' => $chofer->getId())))
            ->setMethod('DELETE')
            ->getForm();
    }
    public function reporteHorasAction(Connection $connection)
    {
        $db = $connection;

        $query = 'SELECT
           chofer.nombre,
           SUM(hoja_ruta.basico) AS horas_basico,
           SUM(hoja_ruta.conincremento) AS horas_conincremento,
           SUM(hoja_ruta.turnopartido) AS horas_turnopartido,
           SUM(hoja_ruta.confronta) AS horas_confronta,
           SUM(hoja_ruta.voluntario) AS horas_voluntario,
           SUM(hoja_ruta.totalhoras) AS totalhorastrabajadas
        FROM
           public.hoja_ruta,
           public.chofer,
           public.omnibus
        WHERE
           hoja_ruta.id_omnibus = omnibus.id AND
           chofer.omnibus_id = omnibus.id
        GROUP BY chofer.nombre';
        $stmt = $db->prepare($query);
        $params = array();
        $stmt->execute($params);
        $reportes = $stmt->fetchAll();
        return $this->render('chofer/reporteHorasTrabajo.html.twig', array(
            'reportes' => $reportes
        ));
    }
}

templates/chofer/edit.html.twig
{% extends 'index.html.twig' %} {% block contenido%}
<br />
{{ form_start(edit_form, { method: "POST" }) }}
<div class="col-md-10 offset-md-1" style="font-size: 0.85rem;">
  <div class="card">
    <div class="card-body">
      <br />
      <div class="col-md-8 offset-md-2">
        <h4 class="text-primary">
          Editar Chofer
        </h4>
        <br />
        <div class="form-group">
          <label class="col-sm-4 control-label">Nombre</label>
          {{ form_widget(edit_form.nombre, 
                {'attr' : {'class' : 'form-control' }}
          )}}
        </div>
        <div class="form-group">
          <label class="col-sm-4 control-label">Licencia de Conducción</label>
          {{ form_widget(edit_form.noLicenciaOperativa, 
                {'attr' : {'class' : 'form-control'}}
          )}}
        </div>
        <div class="form-group">
          <label class="col-sm-4 control-label">Ómibus</label>
          {{ form_widget(edit_form.omnibus, 
            {'attr' : {'class' : 'form-control'}}
          )}}
        </div>
        <div class="form-row">
          <div class="col">
            <div class="form-group">
              <label class="control-label">LC Emitida</label>
              {{ form_widget(edit_form.licencia_emision, 
                    {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label class="control-label">LC Vence</label>
              {{ form_widget(edit_form.licencia_vencimiento,
                    {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <div class="form-group">
              <label class="control-label">Recalificación Emitida</label>
              {{ form_widget(edit_form.recalificacion_emision,
                     {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label class="control-label">Recalificación Vence</label>
              {{ form_widget(edit_form.recalificacionVencimiento, 
                    {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <div class="form-group">
              <label class="control-label">Examen Médico Emitido</label>
              {{ form_widget(edit_form.examenMedicoEmision, 
                    {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label class="control-label">Examen Médico Vence</label>
              {{ form_widget(edit_form.examenMedicoVencimiento,
                     {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col">
            <div class="form-group">
              <label class="control-label"
                >Examen Psicofisiológico Emitido</label
              >
              {{ form_widget(edit_form.examenPsicofisiologicoEmision, 
                    {'attr' : {'class' : 'form-control datepicker-here'}}
              )}}
            </div>
          </div>
          <div class="col">
            <div class="form-group">
              <label class="control-label">Examen Psicofisiológico Vence</label>
              {{ form_widget(edit_form.examenPsicofisiologicoVencimiento, 
                    {'attr' : {'class' : 'form-control datepicker-here','data-language':'es'}}
              )}}
            </div>
          </div>
        </div>
        <br />
        <div class="text-right">
          <a
            class="btn btn-outline-secondary"
            href="{{ path('chofer_index') }}"
          >
            Cancelar
          </a>
          <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
      </div>
    </div>
  </div>
  <br />
  {{ form_end(edit_form) }}
</div>
{% endblock %}

templates/chofer/index.html.twig
{% extends 'index.html.twig' %} {% block contenido %}
<br />
<div class="card shadow">
  <div class="card-header py-3">
    <div class="row">
      <div class="col-md-6">
        <h3 class="m-0 text-primary">Choferes</h3>
      </div>
    </div>
  </div>
  <div class="card-body" style="font-size: 0.65rem;">
    <div class="table responsive">
      <table
        class="table text-center"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <th class="text-center">Nombre y Apellidos</th>
          <th class="text-center">CI</th>
          <th class="text-center">Código Trabajador</th>
          <th class="text-center">No. Licencia Conducción</th>
          <th class="text-center">Licencia Conducción Vence</th>
          <th class="text-center">Examen Médico Vence</th>
          <th class="text-center">Examen Psicofisiológico Vence</th>
          <th class="text-center">
            Acciones
          </th>
        </thead>
        <tbody class="text-center">
          {% for reporte in reportes %}
          <tr>
            <td>{{ reporte.nombre }}</td>
            <td>{{ reporte.ci }}</td>
            <td>{{ reporte.codigo }}</td>
            <td>{{ reporte.nolicenciaoperativa }}</td>
            <td>
              {% if reporte.licenciavencimiento %}
              {{ reporte.licenciavencimiento }}
              &nbsp; {% if date(reporte.licenciavencimiento) > date() and
              date(reporte.licenciavencimiento) < date('+7days') %}
              <span
                class="badge badge-pill badge-warning"
                data-tooltip="A punto de vencerse"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% if date(reporte.licenciavencimiento) < date() %}
              <span
                class="badge badge-pill badge-danger"
                data-tooltip="Documento vencido"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% endif %}
            </td>
            <td>
              {% if reporte.examenmedicovencimiento %}
              {{ reporte.examenmedicovencimiento }}
              &nbsp; {% if date(reporte.examenmedicovencimiento) > date() and
              date(reporte.examenmedicovencimiento) < date('+7days') %}
              <span
                class="badge badge-pill badge-warning"
                data-tooltip="A punto de vencerse"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% if date(reporte.examenmedicovencimiento) < date()
              %}
              <span
                class="badge badge-pill badge-danger"
                data-tooltip="Documento vencido"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% endif %}
            </td>
            <td>
              {% if reporte.examenpsicofisiologicovencimiento %}
              {{ reporte.examenpsicofisiologicovencimiento }}
              &nbsp; {% if date(reporte.examenpsicofisiologicovencimiento) >
              date() and date(reporte.examenpsicofisiologicovencimiento) <
              date('+7days') %}
              <span
                class="badge badge-pill badge-warning"
                data-tooltip="A punto de vencerse"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% if date(reporte.examenpsicofisiologicovencimiento)
              < date() %}
              <span
                class="badge badge-pill badge-danger"
                data-tooltip="Documento vencido"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% endif %}
            </td>
            <td>
              <div class="row">
                <div class="col text-center">
                  <a
                    href="{{
                      path('chofer_show', { id: reporte.trabajador_id })
                    }}"
                    class="text-secondary"
                    data-tooltip="Visualizar"
                    data-tooltip-location="top"
                    ><i class="fas fa-eye"></i>
                  </a>
                </div>
                {% if is_granted('ROLE_ADMIN' ) or
                is_granted('ROLE_ESPECIALISTA_OPERACIONES' ) %}
                <div class="col text-center">
                  <a
                    href="{{
                      path('chofer_edit', { id: reporte.trabajador_id })
                    }}"
                    data-tooltip="Editar"
                    data-tooltip-location="top"
                    ><i class="fas fa-edit"></i>
                  </a>
                </div>
                {% endif %}
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

templates/chofer/reporteHorasTrabajo.html.twig
{% extends 'index.html.twig' %} {% block contenido %}
<br />
<div class="card shadow">
  <div class="card-header py-3">
    <h3 class="m-0 text-primary">
      Resumen de horas trabajadas por chofer
    </h3>
  </div>
  <div class="card-body">
    <div class="table-reponsive">
      <table
        class="table text-center"
        id="dataTable"
        width="100%"
        cellspacing="0"
        style="font-size:0.85rem;"
      >
        <thead>
          <tr>
            <th>Chofer</th>
            <th>Básico</th>
            <th>Con incremento</th>
            <th>Confronta</th>
            <th>Turno Partido</th>
            <th>Voluntario</th>
            <th>Total de Horas</th>
          </tr>
        </thead>
        <tbody>
          {% for reporte in reportes %}
          <tr>
            <td>{{ reporte.nombre }}</td>
            <td>{{ reporte.horas_basico }}</td>
            <td>{{ reporte.horas_conincremento }}</td>
            <td>{{ reporte.horas_turnopartido }}</td>
            <td>{{ reporte.horas_confronta }}</td>
            <td>{{ reporte.horas_voluntario }}</td>
            <td>{{ reporte.totalhorastrabajadas }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

templates/chofer/show.html.twig
{% extends 'index.html.twig' %} {% block contenido%}
<br />
<div class="col-md-10 offset-md-1">
  <div class="card shadow">
    <div class="card-header">
      <div class="row">
        <div class="col-md-6">
          <h3>{{ chofer.nombre }}</h3>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-12">
          Chofer del ómnibus {{ chofer.omnibus ? chofer.omnibus : "n/a" }} con
          licencia de conducción
          {{ chofer.noLicenciaOperativa ? chofer.noLicenciaOperativa : "n/a" }}
        </div>
      </div>
      <br />
      <div class="row mb-3">
        <div class="col-md-6">
          <strong>Recalificación Emitida:</strong>
          {% if chofer.recalificacionEmision %}
          {{ chofer.recalificacionEmision|date('Y-m-d') }}
          {% endif %}
        </div>
        <div class="col-md-6">
          <strong> Recalificación Vence:</strong>
          {% if chofer.recalificacionVencimiento %}
          {{ chofer.recalificacionVencimiento|date('Y-m-d')}}
          {% endif %}
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-6">
          <strong>Examen Médico Emitido:</strong>
          {% if chofer.examenMedicoEmision %}
          {{ chofer.examenMedicoEmision|date('Y-m-d')}}
          {% endif %}
        </div>
        <div class="col-md-6">
          <strong>Examen Médico Vence:</strong>
          {% if chofer.examenMedicoVencimiento %}
          {{ chofer.examenMedicoVencimiento|date('Y-m-d')}}
          {% endif %}
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-6">
          <strong>Examen Psicofisiológico Emitido:</strong>
          <td>
            {% if chofer.examenPsicofisiologicoEmision %}
            {{ chofer.examenPsicofisiologicoEmision|date('Y-m-d')}}
            {% endif %}
          </td>
        </div>

        <div class="col-md-6">
          <strong>Examen Psicofisiológico Vence:</strong>
          <td>
            {% if chofer.examenPsicofisiologicoVencimiento %}
            {{ chofer.examenPsicofisiologicoVencimiento|date('Y-m-d')}}
            {% endif %}
          </td>
        </div>
      </div>
      <div class="row mb-3">
        <div class="col-md-6">
          <strong>LC Emitida:</strong>
          {% if chofer.licenciaEmision %}
          {{ chofer.licenciaEmision|date('Y-m-d')}}
          {% endif %}
        </div>
        <div class="col-md-6">
          <strong>LC Vence:</strong>
          {% if chofer.licenciaVencimiento %}
          {{ chofer.licenciaVencimiento|date('Y-m-d')}}
          {% endif %}
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="text-right">
        <a
          href="{{ path('chofer_edit', { id: chofer.id }) }}"
          class="btn btn-outline-secondary"
          data-toggle="tooltip"
          data-placement="left"
          title="Editar elemento"
        >
          Editar
        </a>
        <a class="btn btn-primary" href="{{ path('chofer_index') }}">
          Atrás
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}