src/Entity/Tipo_omnibus.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Tipo_omnibus
 *
 * @ORM\Table(name="tipo_omnibus")
 * @ORM\Entity(repositoryClass="App\Repository\Tipo_omnibusRepository")
 */
class Tipo_omnibus
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="tipo", type="string", length=255)
     */
    private $tipo;
    /**
     * @var int
     *
     * @ORM\Column(name="desviacion", type="integer")
     */
    private $desviacion;

    /**
     * @var float
     *
     * @ORM\Column(name="indiceConsumoNormado", type="float")
     */
    private $indiceConsumoNormado;
    /**
     * @var int
     *
     * @ORM\Column(name="cantidadkmtsxlitro", type="integer")
     */
    private $cantidadKmtsXlitro;
    /**
     * @var int
     *
     * @ORM\Column(name="capacidad_total", type="integer", nullable=true)
     */
    private $capacidad_total;

    /**
     * @var int
     *
     * @ORM\Column(name="capacidad_sentados", type="integer")
     */
    private $capacidad_sentados;

    /**
     * @var int
     *
     * @ORM\Column(name="capacidad_parados", type="integer")
     */
    private $capacidad_parados;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Omnibus", mappedBy="typeOmnibus")
     */
    protected $omnibus;

    public function __toString()
    {
        return $this->tipo;
    }


    /**
     * Constructor
     */
    public function __construct()
    {
        $this->omnibus = new \Doctrine\Common\Collections\ArrayCollection();
    }


    /**
     * Add omnibus
     *
     * @param \App\Entity\Omnibus $omnibus
     *
     * @return Tipo_omnibus
     */
    public function addOmnibus(\App\Entity\Omnibus $omnibus)
    {
        $this->omnibus[] = $omnibus;

        return $this;
    }

    /**
     * Remove omnibus
     *
     * @param \App\Entity\Omnibus $omnibus
     */
    public function removeOmnibus(\App\Entity\Omnibus $omnibus)
    {
        $this->omnibus->removeElement($omnibus);
    }

    /**
     * @return int
     */
    public function getCantidadKmtsXlitro()
    {
        return $this->cantidadKmtsXlitro;
    }

    /**
     * @param int $cantidadKmtsXlitro
     */
    public function setCantidadKmtsXlitro($cantidadKmtsXlitro)
    {
        $this->cantidadKmtsXlitro = $cantidadKmtsXlitro;
    }


    /**
     * @return int
     */
    public function getCapacidadParados()
    {
        return $this->capacidad_parados;
    }

    /**
     * @param int $capacidad_parados
     */
    public function setCapacidadParados($capacidad_parados)
    {
        $this->capacidad_parados = $capacidad_parados;
    }

    /**
     * @return int
     */
    public function getCapacidadSentados()
    {
        return $this->capacidad_sentados;
    }

    /**
     * @param int $capacidad_sentados
     */
    public function setCapacidadSentados($capacidad_sentados)
    {
        $this->capacidad_sentados = $capacidad_sentados;
    }

    /**
     * @return int
     */
    public function getCapacidadTotal()
    {
        return $this->capacidad_total;
    }

    /**
     * @param int $capacidad_total
     */
    public function setCapacidadTotal($capacidad_total)
    {
        $this->capacidad_total = $capacidad_total;
    }

    /**
     * @return int
     */
    public function getDesviacion()
    {
        return $this->desviacion;
    }

    /**
     * @param int $desviacion
     */
    public function setDesviacion($desviacion)
    {
        $this->desviacion = $desviacion;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return float
     */
    public function getIndiceConsumoNormado()
    {
        return $this->indiceConsumoNormado;
    }

    /**
     * @param float $indiceConsumoNormado
     */
    public function setIndiceConsumoNormado($indiceConsumoNormado)
    {
        $this->indiceConsumoNormado = $indiceConsumoNormado;
    }

    /**
     * @return mixed
     */
    public function getOmnibus()
    {
        return $this->omnibus;
    }

    /**
     * @param mixed $omnibus
     */
    public function setOmnibus($omnibus)
    {
        $this->omnibus = $omnibus;
    }

    /**
     * @return string
     */
    public function getTipo()
    {
        return $this->tipo;
    }

    /**
     * @param string $tipo
     */
    public function setTipo($tipo)
    {
        $this->tipo = $tipo;
    }
}

src/Form/Tipo_omnibusType.php
<?php

namespace App\Form;

use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Tipo_omnibusType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('tipo')
            ->add('capacidad_sentados')
            ->add('capacidad_parados')
            ->add('indiceConsumoNormado')
            ->add('desviacion')
            ->add('cantidadkmtsxlitro', IntegerType::class, ['required' => true]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\Entity\Tipo_omnibus'
        ));
    }
}

src/Controller/Tipo_omnibusController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Entity\Tipo_omnibus;
use App\Form\Tipo_omnibusType;

// * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_ESPECIALISTA_OPERACIONES')")
/**
 *
 * Función para llamar a la plantilla de administración
 *
 */
class Tipo_omnibusController extends AbstractController
{
    /**
     * Lists all Tipo_omnibus entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $tipo_omnibuses = $em->getRepository('App:Tipo_omnibus')->findAll();

        return $this->render('tipo_omnibus/index.html.twig', array(
            'tipo_omnibuses' => $tipo_omnibuses,
        ));
    }

    /**
     * Creates a new Tipo_omnibus entity.
     *
     */
    public function newAction(Request $request)
    {
        $tipo_omnibus = new Tipo_omnibus();
        $form = $this->createForm('App\Form\Tipo_omnibusType', $tipo_omnibus);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $capacidadTotal = $tipo_omnibus->getCapacidadSentados() + $tipo_omnibus->getCapacidadParados();
            $tipo_omnibus->setCapacidadTotal($capacidadTotal);

            $em->persist($tipo_omnibus);
            $em->flush();

            $this->addFlash('notice', 'Se ha insertado correctamente!');

            return $this->redirectToRoute('tipo_omnibus_index', array('id' => $tipo_omnibus->getId()));
        } else if ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('error', 'Ha ocurrido algún error al insertar');
        }

        return $this->render('tipo_omnibus/new.html.twig', array(
            'tipo_omnibus' => $tipo_omnibus,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Tipo_omnibus entity.
     *
     */
    public function showAction(Tipo_omnibus $tipo_omnibus)
    {
        //        $deleteForm = $this->createDeleteForm($tipo_omnibus);

        return $this->render('tipo_omnibus/show.html.twig', array(
            'tipo_omnibus' => $tipo_omnibus,
            //            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Tipo_omnibus entity.
     *
     */
    public function editAction(Request $request, Tipo_omnibus $tipo_omnibus)
    {
        $editForm = $this->createForm('App\Form\Tipo_omnibusType', $tipo_omnibus);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $capacidadTotal = $tipo_omnibus->getCapacidadSentados() + $tipo_omnibus->getCapacidadParados();
            $tipo_omnibus->setCapacidadTotal($capacidadTotal);

            $em->persist($tipo_omnibus);
            $em->flush();

            $this->addFlash('notice', 'Se ha editado correctamente!');

            return $this->redirectToRoute('tipo_omnibus_index', array('id' => $tipo_omnibus->getId()));
        } else if ($editForm->isSubmitted() && !$editForm->isValid()) {
            $this->addFlash('error', 'Ha ocurrido algún error al editar');
        }

        return $this->render('tipo_omnibus/edit.html.twig', array(
            'tipo_omnibus' => $tipo_omnibus,
            'edit_form' => $editForm->createView(),
        ));
    }

    /**
     * Deletes a Tipo_omnibus entity.
     *
     */
    public function deleteAction(Request $request, Tipo_omnibus $tipo_omnibus)
    {
        //        $form = $this->createDeleteForm($tipo_omnibus);
        //        $form->handleRequest($request);

        //        if ($form->isSubmitted() && $form->isValid()) {
        $em = $this->getDoctrine()->getManager();
        $em->remove($tipo_omnibus);
        $em->flush();
        //        }

        $this->addFlash('notice', 'Se ha borrado correctamente!');

        return $this->redirectToRoute('tipo_omnibus_index');
    }

    /**
     * Creates a form to delete a Tipo_omnibus entity.
     *
     * @param Tipo_omnibus $tipo_omnibus The Tipo_omnibus entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Tipo_omnibus $tipo_omnibus)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('tipo_omnibus_delete', array('id' => $tipo_omnibus->getId())))
            ->setMethod('DELETE')
            ->getForm();
    }
}

templates/tipo_omnibus/edit.html.twig
{% extends 'index.html.twig' %} {% block contenido %}
<br />
<div class="col-md-10 offset-md-1" style="font-size: 0.85rem;">
  {{ form_start(edit_form, { method: "POST" }) }}
  <div class="card shadow">
    <div class="card-body">
      <div class="col-md-10 offset-md-1">
        <h4 class="text-primary">Editar Marca de Ómnibus</h4>
        <br />
        <div class="form-group">
          <label class="col-sm-4 control-label">Marca</label>
          {{ form_widget(edit_form.tipo, 
          {'attr' : {'class' : 'form-control','pattern':'[A-Za-z]+$'}}
          )}}
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">Capacidad pasajeros sentados</label>
              {{ form_widget(edit_form.capacidad_sentados, 
              {'attr' : {'class' : 'form-control','pattern':'[0-9]{2,3}'}}
              )}}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">Capacidad pasajeros parados</label>
              {{ form_widget(edit_form.capacidad_parados, 
              {'attr' : {'class' : 'form-control','pattern':'[0-9]{2,3}'}}
              )}}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label"
                >Índice de Consumo Normado por Kms</label
              >
              {{ form_widget(edit_form.indiceConsumoNormado,
             {'attr' : {'class' : 'form-control','pattern':'([0-9.]+)$'}}
              )}}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">% de Desviación</label>
              {{ form_widget(edit_form.desviacion, 
            {'attr' : {'class' : 'form-control','pattern':'([0-9%]){2,3}'}}
              )}}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label"
                >Cant de Kmts X Litro Combust. - norma</label
              >
              {{
              form_widget(edit_form.cantidadkmtsxlitro, {
                attr: { class: "form-control", pattern: "([0-9.]+)$" },
              })
              }}
            </div>
          </div>
        </div>
        <br />
        <div class="text-right">
          <a
            class="btn btn-outline-secondary"
            href="{{ path('tipo_omnibus_index') }}"
          >
            Cancelar
          </a>
          <button type="submit" class="btn btn-primary" value="Editar">
            Guardar
          </button>
        </div>
      </div>
      <br />
    </div>
  </div>
  {{ form_end(edit_form) }}
</div>
{% endblock %}

templates/tipo_omnibus/index.html.twig
{% extends 'index.html.twig' %} {% block contenido %}
<br />
<div class="card shadow">
  <div class="card-header py-3">
    <div class="row">
      <div class="col-md-6">
        <h3 class="m-0 text-primary">Marcas de ómnibus</h3>
      </div>
      <div class="col-md-6 text-right">
        {% if is_granted('ROLE_ADMIN' ) or
        is_granted('ROLE_ESPECIALISTA_OPERACIONES' ) %}
        <a
          class="btn btn-sm btn-default pull-left"
          href="{{ path('tipo_omnibus_new') }}"
        >
          <img
            src="{{ asset('assets/dist/img/add_database_26px.png') }}"
            alt="User Image"
          />
          Nuevo
        </a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table text-center"
        id="dataTable"
        width="100%"
        cellspacing="0"
        style="font-size: 0.75rem;"
      >
        <thead>
          <th>Marca</th>
          <th>Capacidad sentados</th>
          <th>Capacidad parados</th>
          <th>Capacidad total</th>
          <th>Índice Consumo Normado por Kms</th>
          <th>% de Desviación</th>
          <th>Cant de Kmts X Litro Combust. - norma</th>
          {% if is_granted('ROLE_ADMIN' ) or
          is_granted('ROLE_ESPECIALISTA_OPERACIONES' ) %}
          <th>
            Acciones
          </th>
          {% endif %}
        </thead>
        <tbody>
          {% for tipo_omnibus in tipo_omnibuses %}
          <tr>
            <td>{{ tipo_omnibus.tipo }}</td>
            <td>{{ tipo_omnibus.capacidadSentados }}</td>
            <td>{{ tipo_omnibus.capacidadParados }}</td>
            <td>{{ tipo_omnibus.capacidadTotal }}</td>
            <td>{{ tipo_omnibus.indiceConsumoNormado }}</td>
            <td>
              {{ tipo_omnibus.desviacion }}
              {% if tipo_omnibus.desviacion <= 5 %} &nbsp;
              <span
                class="badge badge-pill badge-danger"
                data-tooltip="Sobreconsumo de combustible"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %} {% if tipo_omnibus.desviacion > 5 %} &nbsp;
              <span
                class="badge badge-pill badge-success"
                data-tooltip="Ahorro de combustible"
                data-tooltip-location="top"
              >
                <i class="fas fa-info"></i>
              </span>
              {% endif %}
            </td>
            <td>{{ tipo_omnibus.cantidadKmtsXlitro }}</td>
            {% if is_granted('ROLE_ADMIN' ) or
            is_granted('ROLE_ESPECIALISTA_OPERACIONES' ) %}
            <td>
              <div class="row">
                <div class="col-md-3 offset-md-1">
                  <a
                    class="text-secondary"
                    href="#"
                    rol="button"
                    data-toggle="modal"
                    data-target="#modalConfirmDelete-{{ tipo_omnibus.id }}"
                    data-tooltip="Eliminar"
                    data-tooltip-location="top"
                  >
                    <i class="fas fa-trash-alt"></i>
                  </a>
                  {% include "commons/confirmDeleteModal.html.twig" with
                  {'instanceToDelete': tipo_omnibus,
                  'path':'tipo_omnibus_delete'} %}
                </div>
                <div class="col-md-3">
                  <a
                    href="{{
                      path('tipo_omnibus_edit', { id: tipo_omnibus.id })
                    }}"
                    class="text-primary"
                    data-tooltip="Editar"
                    data-tooltip-location="top"
                    ><i class="fas fa-edit"></i>
                  </a>
                </div>
              </div>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<div id="mymodal" class="modal inmodal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button
          aria-label="Close"
          data-dismiss="modal"
          class="close"
          type="button"
        >
          <span aria-hidden="true">×</span>
        </button>
        <i class="fa-3x fa fa-warning modal-icon text-red"></i>
        <h4 class="modal-title">Acción Peligrosa</h4>
      </div>
      <div class="modal-body">
        <p>
          Está acción puede ocacionar, comprometer la integridad de los datos!
        </p>
        <small
          >Si no es un usuario avanzado, recomendamos que cancele esta
          acción.</small
        >
      </div>
      <div class="modal-footer">
        <button data-dismiss="modal" class="btn btn-primary" type="button">
          Cerrar
        </button>
        <a class="btn btn-primary btn-danger btn-delete" href="#">Eliminar</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/tipo_omnibus/new.html.twig
{% extends 'index.html.twig' %} {% block contenido %}
<br />
<div class="col-md-10 offset-md-1" style="font-size: 0.85rem;">
  {{ form_start(form, { method: "POST" }) }}
  <div class="card shadow">
    <div class="card-body">
      <div class="col-md-10 offset-md-1">
        <h4 class="text-primary">Nueva Marca de Ómnibus</h4>
        <br />
        <div class="form-group">
          <label class="col-sm-4 control-label">Marca</label>
          {{ form_widget(form.tipo, 
            {'attr' : {'class' : 'form-control','pattern':'[A-Za-z]+$'}}
          )}}
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">Capacidad pasajeros sentados</label>
              {{ form_widget(form.capacidad_sentados,
                  {'attr' : {'class' : 'form-control','pattern':'[0-9]{2,3}' }}
              )}}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">Capacidad pasajeros parados</label>
              {{
                form_widget(form.capacidad_parados, {
                  attr: { class: "form-control", pattern: "[0-9]{2,3}" }
                })
              }}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label"
                >Índice de Consumo Normado por Kms</label
              >
              {{ form_widget(form.indiceConsumoNormado, 
              {'attr' : {'class' : 'form-control','pattern':'([0-9,]+)$'}}
              )}}
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label">% de Desviación</label>
              {{ form_widget(form.desviacion,
               {'attr' : {'class' : 'form-control','pattern':'([0-9%]){2,3}' }}
              )}}
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label"
                >Cant de Kmts X Litro Combust. - norma</label
              >
              {{ form_widget(form.cantidadkmtsxlitro,
              {'attr' : {'class' : 'form-control','pattern':'([0-9,]+)$'}}
              )}}
            </div>
          </div>
        </div>
        <br />
        <div class="text-right">
          <a
            class="btn btn-outline-secondary"
            href="{{ path('tipo_omnibus_index') }}"
          >
            Cancelar
          </a>
          <button type="submit" class="btn btn-primary" value="Crear">
            Guardar
          </button>
        </div>
      </div>
      <br />
    </div>
  </div>
  {{ form_end(form) }}
</div>
{% endblock %}

templates/tipo_omnibus/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Tipo_omnibus</h1>
    <td>{{ tipo_omnibus.capacidad_sentados }}</td>
    <td>{{ tipo_omnibus.capacidad_parados }}</td>
    <td>{{ tipo_omnibus.capacidad_total }}</td>
    <td>{{ tipo_omnibus.indiceConsumoNormado }}</td>
    <td>{{ tipo_omnibus.desviacion }}</td>
    <td>{{ tipo_omnibus.cantidadCombustiblelitros }}</td>
    <table>
        <tbody>
            <tr>
                <th>Tipo ómnibus</th>
                <td>{{ tipo_omnibus.tipo }}</td>
            </tr>
            <tr>
                <th>Capacidad sentad</th>
                <td>{{ tipo_omnibus.capacidad_sentados }}</td>
            </tr>
            <tr>
                <th>Indiceconsumo</th>
                <td>{{ tipo_omnibus.indiceConsumo }}</td>
            </tr>
        </tbody>
    </table>

    <ul>
        <li>
            <a href="{{ path('tipo_omnibus_index') }}">Back to the list</a>
        </li>
        <li>
            <a href="{{ path('tipo_omnibus_edit', { 'id': tipo_omnibus.id }) }}">Edit</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}